name: .NET Continuous delivery
on: push
jobs:
  deploy-template:
    name: Deploy Bicep template to Azure
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - uses: azure/login@v1
        name: Login to Azure CLI
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/checkout@v3
        name: Checkout external repository code
        with:
          repository: wahabu/aprilsixthdeploy
      - run: |
          az deployment group create \
            --resource-group aprilsixth \
            --template-file container.bicep \
            --name autodeploy-${{ github.run_number }}
        name: Deploy Bicep template using Azure CLI
  build-container:
    name: Build and push Docker container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository code
      - uses: docker/login-action@v2
        name: Login to ACR
        with:
          registry: reactoronthesixth.azurecr.io
          username: ${{ secrets.DOCKER_REGISTRY_IDENTIFIER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v4
        name: Build and push to ACR
        with:
          context: .
          push: true
          tags: |
            reactoronthesixth.azurecr.io/aspnetrazor:latest
            reactoronthesixth.azurecr.io/aspnetrazor:${{github.run_number }}
