name: .NET Continuous delivery
on: push
jobs:
  build-container:
    name: Build and push Docker container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository code
      - uses: docker/login-action@v2
        name: Login to ACR
        with:
          registry: reactoronthesixth.azurecr.io
          username: ${{ secrets.DOCKER_REGISTRY_IDENTIFIER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v4
        name: Build and push to ACR
        with:
          context: .
          push: true
          tags: |
            reactoronthesixth.azurecr.io/aspnetrazor:latest
            reactoronthesixth.azurecr.io/aspnetrazor:${{github.run_number }}
